volumes:
  postgresdb:

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: deploymentdb
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    restart: always
